### ISSUE TITLE
Sign with hedera provided key

### ISSUE THREAD

**Issue by boylove142** [calvinchengx/hedera-sdk-js#1]
Hi, did you try to sign with hedera provided key `302e020100300506032b657004220420a491f838e78...` because it seems the key is encoded and not compatible with your ed25519 library.

**Comment by calvinchengx** [comment]
Hello, 

The example key you provided is DER-encoded.

It needs to be transformed into a format that node-forge understands first.

I should have a transformation function somewhere. Will share it later.

**Comment by calvinchengx** [comment]
@boylove142 here's the conversion function - https://github.com/calvinchengx/hedera-sdk-js/blob/25a0793057d73ebab644e2d4218c30e7755a117f/src/keypair.ts#L68

BTW, I haven't had time to update this repo and get everything working properly. 

Will do so soon.

**Comment by boylove142** [comment]
Thank you so much @calvinchengx, will try this and back to you soon.
